using SourceGenerator.ProtoDefTypes;
using System.Text;

public class ProtocolGenerator
{
	private readonly Namespace _namespace;
	private readonly string _version;
	private readonly int _numberVersion;
	public ProtocolGenerator(Namespace ns, string version, int numberVersion)
	{
		_namespace = ns;
		_numberVersion = numberVersion;
		_version = version;
	}

	public async Task Generate()
	{


		string fileHeader = new StringBuilder()
			.AppendLine("// Generated by Titlehhhh")
			.ToString();

		string namespaceName = $"McProtoNet.Protocol_{_numberVersion}";


	}
}
