using System.Text;
using SourceGenerator.ProtoDefTypes;

public class ProtocolGenerator
{
    private readonly Namespace _namespace;
    private readonly int _numberVersion;
    private readonly string _version;

    public ProtocolGenerator(Namespace ns, string version, int numberVersion)
    {
        _namespace = ns;
        _numberVersion = numberVersion;
        _version = version;
    }

    public async Task Generate()
    {
        var fileHeader = new StringBuilder()
            .AppendLine("// Generated by Titlehhhh")
            .ToString();

        var namespaceName = $"McProtoNet.Protocol_{_numberVersion}";
    }
}