//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerOpenHorseWindowPacket
{
	public byte WindowId { get; set; }
	public int NbSlots { get; set; }
	public int EntityId { get; set; }
}
