//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerNamedSoundEffectPacket
{
	public string SoundName { get; set; }
	public int SoundCategory { get; set; }
	public int X { get; set; }
	public int Y { get; set; }
	public int Z { get; set; }
	public float Volume { get; set; }
	public float Pitch { get; set; }
}
