//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerCollectPacket
{
	public int CollectedEntityId { get; set; }
	public int CollectorEntityId { get; set; }
	public int PickupItemCount { get; set; }
}
