//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerUpdateHealthPacket
{
	public float Health { get; set; }
	public int Food { get; set; }
	public float FoodSaturation { get; set; }
}
