//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerSpawnEntityExperienceOrbPacket
{
	public int EntityId { get; set; }
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
	public short Count { get; set; }
}
