//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerEntityTeleportPacket
{
	public int EntityId { get; set; }
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
	public sbyte Yaw { get; set; }
	public sbyte Pitch { get; set; }
	public bool OnGround { get; set; }
}
