//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerCraftProgressBarPacket
{
	public byte WindowId { get; set; }
	public short Property { get; set; }
	public short Value { get; set; }
}
