//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerExperiencePacket
{
	public float ExperienceBar { get; set; }
	public int Level { get; set; }
	public int TotalExperience { get; set; }
}
