//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerEntitySoundEffectPacket
{
	public int SoundId { get; set; }
	public int SoundCategory { get; set; }
	public int EntityId { get; set; }
	public float Volume { get; set; }
	public float Pitch { get; set; }
}
