//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerEntityEffectPacket
{
	public int EntityId { get; set; }
	public sbyte EffectId { get; set; }
	public sbyte Amplifier { get; set; }
	public int Duration { get; set; }
	public sbyte HideParticles { get; set; }
}
