//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerTransactionPacket
{
	public sbyte WindowId { get; set; }
	public short Action { get; set; }
	public bool Accepted { get; set; }
}
