//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerOpenWindowPacket
{
	public int WindowId { get; set; }
	public int InventoryType { get; set; }
	public string WindowTitle { get; set; }
}
