//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerEntityLookPacket
{
	public int EntityId { get; set; }
	public sbyte Yaw { get; set; }
	public sbyte Pitch { get; set; }
	public bool OnGround { get; set; }
}
