//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerVehicleMovePacket
{
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
	public float Yaw { get; set; }
	public float Pitch { get; set; }
}
