//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerEntityVelocityPacket
{
	public int EntityId { get; set; }
	public short VelocityX { get; set; }
	public short VelocityY { get; set; }
	public short VelocityZ { get; set; }
}
