//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ServerAbilitiesPacket
{
	public sbyte Flags { get; set; }
	public float FlyingSpeed { get; set; }
	public float WalkingSpeed { get; set; }
}
