//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientSteerVehiclePacket
{
	public float Sideways { get; set; }
	public float Forward { get; set; }
	public byte Jump { get; set; }
}
