//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientSettingsPacket
{
	public string Locale { get; set; }
	public sbyte ViewDistance { get; set; }
	public int ChatFlags { get; set; }
	public bool ChatColors { get; set; }
	public byte SkinParts { get; set; }
	public int MainHand { get; set; }
}
