//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientPositionPacket
{
	public double X { get; set; }
	public double Y { get; set; }
	public double Z { get; set; }
	public bool OnGround { get; set; }
}
