//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientUpdateCommandBlockMinecartPacket
{
	public int EntityId { get; set; }
	public string Command { get; set; }
	public bool TrackOutput { get; set; }
}
