//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientCraftRecipeRequestPacket
{
	public sbyte WindowId { get; set; }
	public string Recipe { get; set; }
	public bool MakeAll { get; set; }
}
