//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientLookPacket
{
	public float Yaw { get; set; }
	public float Pitch { get; set; }
	public bool OnGround { get; set; }
}
