//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientRecipeBookPacket
{
	public int BookId { get; set; }
	public bool BookOpen { get; set; }
	public bool FilterActive { get; set; }
}
