//AutoGenerated

namespace McProtoNet.Packets;

public sealed class ClientEntityActionPacket
{
	public int EntityId { get; set; }
	public int ActionId { get; set; }
	public int JumpBoost { get; set; }
}
